# Generated by Django 4.1.4 on 2022-12-06 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='session_token',
        ),
        migrations.AddField(
            model_name='employee',
            name='email',
            field=models.EmailField(default=2, max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
