# Generated by Django 4.1.4 on 2022-12-06 15:05

from django.db import migrations, models
import employee.models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_remove_user_session_token_employee_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='ACNumber',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='DOB',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='IFSCNumber',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='aadharNumber',
            field=models.CharField(default=0, max_length=12, validators=[employee.models.validate_aadhar]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='bankName',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='branchName',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='designation',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, error_messages={'unique': 'A user with this phone number already exists.'}, max_length=128, null=True, region=None, unique=True, verbose_name='phone number'),
        ),
        migrations.AddField(
            model_name='employee',
            name='photo',
            field=models.ImageField(null=True, upload_to='profilepic'),
        ),
        migrations.AddField(
            model_name='employee',
            name='salary',
            field=models.IntegerField(default=0),
        ),
    ]
